CREATE DATABASE IF NOT EXISTS cinephoria
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE cinephoria;

CREATE TABLE IF NOT EXISTS Usuario (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_usuario_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
